name: Java CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 for Gradle
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: 'gradle'
    - name: Build with Gradle
      run: gradle build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CL-Toolbox
        path: build/libs/cl-toolbox-0.0.1-SNAPSHOT.jar

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Publish package
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
