name: Java CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: gradle build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: CL-Toolbox
        path: build/libs/CL-Toolbox.jar
